Unauthorized: /api/v1/dslamport/search_fqdns/
Not Found: /api/v1/dslamport/get_partak_dslam_list_by_telecom_id/
Internal Server Error: /api/v1/dslamport/register-port/
Internal Server Error: /api/v1/dslamport/register-port/
Internal Server Error: /api/v1/dslamport/register-port/
Internal Server Error: /api/v1/contact/get_ddr_info_exportExcel/
Traceback (most recent call last):
  File "/home/mrtbadboy/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mrtbadboy/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/mrtbadboy/.local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/mrtbadboy/.local/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/mrtbadboy/.local/lib/python3.9/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/mrtbadboy/.local/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/mrtbadboy/.local/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type FarzaneganTDLTE is not JSON serializable
Not Found: /favicon.ico
Unauthorized: /api/v1/dslamport/run-command/
